// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwyW2G7Ncpzfs1sarQBGNi1zOgGCrF-GU',
    appId: '1:1087715237909:web:e8b265014d64d0f8222e1c',
    messagingSenderId: '1087715237909',
    projectId: 'my-spotify-music-app',
    authDomain: 'my-spotify-music-app.firebaseapp.com',
    storageBucket: 'my-spotify-music-app.appspot.com',
    measurementId: 'G-4R77M01EN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcUKQnp--hOiwOFCIFwfDsyz7fzzWztjA',
    appId: '1:1087715237909:android:4da7711c4a13b799222e1c',
    messagingSenderId: '1087715237909',
    projectId: 'my-spotify-music-app',
    storageBucket: 'my-spotify-music-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATlkB_lqOSX5fHI1FEIJzrBnIvV3ZF3BY',
    appId: '1:1087715237909:ios:f1057250b5c7f90f222e1c',
    messagingSenderId: '1087715237909',
    projectId: 'my-spotify-music-app',
    storageBucket: 'my-spotify-music-app.appspot.com',
    iosBundleId: 'com.example.musium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATlkB_lqOSX5fHI1FEIJzrBnIvV3ZF3BY',
    appId: '1:1087715237909:ios:f1057250b5c7f90f222e1c',
    messagingSenderId: '1087715237909',
    projectId: 'my-spotify-music-app',
    storageBucket: 'my-spotify-music-app.appspot.com',
    iosBundleId: 'com.example.musium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwyW2G7Ncpzfs1sarQBGNi1zOgGCrF-GU',
    appId: '1:1087715237909:web:bc452af3b32aeac6222e1c',
    messagingSenderId: '1087715237909',
    projectId: 'my-spotify-music-app',
    authDomain: 'my-spotify-music-app.firebaseapp.com',
    storageBucket: 'my-spotify-music-app.appspot.com',
    measurementId: 'G-P6T584CZXC',
  );
}
